export const topTeachersData = [
  {
    id: 1,
    rating: 4.8,
    name: 'Alisher',
    surname: 'Navoiy',
    position: 'Professor',
  },
  {
    id: 2,
    rating: 4.7,
    name: 'Zokir',
    surname: 'Rasulov',
    position: 'Associate Professor',
  },
  {
    id: 3,
    rating: 4.9,
    name: 'Shodiyor',
    surname: "Toshpo'latov",
    position: 'Senior Lecturer',
  },
  {
    id: 4,
    rating: 4.5,
    name: 'Gulchehra',
    surname: 'Sodiqova',
    position: 'Lecturer',
  },
  {
    id: 5,
    rating: 4.6,
    name: 'Olimjon',
    surname: "Turg'unov",
    position: 'Professor',
  },
  {
    id: 6,
    rating: 4.7,
    name: 'Madina',
    surname: 'Karimova',
    position: 'Associate Professor',
  },
  {
    id: 7,
    rating: 4.8,
    name: 'Javlon',
    surname: 'Yusupov',
    position: 'Senior Lecturer',
  },
  {
    id: 8,
    rating: 4.9,
    name: 'Saida',
    surname: 'Niyozova',
    position: 'Lecturer',
  },
  {
    id: 9,
    rating: 4.6,
    name: 'Oybek',
    surname: 'Raxmatov',
    position: 'Professor',
  },
  {
    id: 10,
    rating: 4.5,
    name: 'Laziza',
    surname: 'Abdullaeva',
    position: 'Associate Professor',
  },
];
